package com.doca.historia;

import java.util.Random;

public class oneFacts2 {
	
	// member variables - properties about the object
	public String [] mAnswers = {
			

			"1D would really love to collaborate with Bruno Mars. They told teen.com: He has great songs, great stage presence, an unbelievable performer. His vocal is  flawless",

			//"1Ds second single Gotta Be You was released on 13th November 2011 and reached number three on the UK chart",
			//"1Ds third single One Thing was released digitally on 6th January 2012 and reached number 28 on the chart.",
			"A little boy proposed to Perrie in Dublin and brought her flowers and ring",
			"According to Liam, Harry is a terrible driver",
			"After a concert I realized that the bus was leaving without me so I was running and screaming and the boys thought I was a fan -Liam ",
			//"After coming third on The X Factor, One Direction were snapped up by Simon Cowells record label Syco",
			"After their first concert with Big Time Rush, lots of people left after they performed",
			"All the boys live within 100 yards of each other in London. Harry and Louis, who are apparently the messiest members of the band, share a house! Wed love to see the state of the place!",
			
			"Apparently, Harry read 'Dark' and told a fan he was looking for Bo",
			"Apparently, Harry's -Hi- tattoo and Louis' -Oops- tattoo are the first things they said to each other in the bathroom where they first met",
			"Apparently, a girl threw a live hamster at Niall during a concert",
			
			"One Direction have 19,114,111 fans on Facebook and 13,886,942 followers on Twitter         August 5 2013, ",
			"At the Las Vegas concert Harry threw a towel at a security guard's face so he and Louis could jump off the stage",
			"Before auditioning for The X Factor, Harry was the frontman of the band White Eskimo which featured his school friends Haydn Morris, Nick Clough and Will Sweeney.",
			"Before they named the band One Direction, Niall suggested they should be called Niall and the Potatoes",
			"Before you judge people, judge yourself.-Zayn",
			"Best Song Ever just came out!:D",
			"Bizarrely, Louis says he likes girls who eat carrots!",
			"Boobear was a singer for the band called 'The Rouge'",
			//"Cardboard cut-outs of the boys are being made",

			"During the X Factor auditions all were students. Niall at Colaiste Mhuire, Zayn at Tong High School, Liam at the City of Wolverhampton College, Harry at Holmes Chapel Comprehensive School and Louis was a sixth former at Hall Cross School",
			"Ed Sheeran (Moments) and American Idol winner Kelly Clarkson (Tell Me A Lie) both penned tracks for Up All Night",
			"Ed Sheeran wrote 'Moments'",
			"Eleanor used to smoke but stopped for Louis",
			"Everyone in One Direction has one or more sisters except for Niall. He is the only one who has a brother",
			"For Harry a romantic date would be tandem bike riding",
			//"Girl: Don't you hate it when you can't find a cheese grater and you have to use your abs?",
			"Girls send Niall's dad their bras so he can take them to Niall to sign",
			//"Had One Direction won The XFactor they would released a cover of the 1984 synthpop anthem Forever Young by Alphaville. 1Ds version leaked online soon after The XFactor.",
			"Harold speaks fluent french :)",
			"Harry Styles was born on 1st February 1994 making him the youngest member of 1D. His star sign is Aquarius ",
			"Harry agreed to pose in a mankini if 'Gotta Be You' goes to number one",
			"Harry and Liam are gym buddies",
			"Harry and Liam can hold a note for 38.02 seconds",
			"Harry and Louis are the only two members of One Direction who have passed their driving test",
			"Harry and Louis first met in the toilets at X Factor",
			"Harry and Louis have already slept naked together :O",
			"Harry and Niall have secret fan accounts so they can communicate with fans",
			"Harry and Zayn have a matching heart tattoo",
			"Harry bought his own tattoo kit so he can give himself tattoos",			
			"Harry came up with the name 'One Direction'",
			"Harry can play the kazoo",
			"Harry carries at least 3 Twix chocolate bars with him",
			"Harry dislike white cars",
			"Harry doesn't like lies and wouldn't lie about having a girlfriend or not",
			"Harry doesn't like mayo.",
			"Harry doesn't like to lie, so he won't lie about having a girlfriend or not",
			"Harry gave his jacket to a fan the other day because it was freezing outside and she was cold. When he gave it to her, she promised to give it back, someday",
			"Harry had a hamster called Hamster",
			"Harry had his first kiss when he was 11",
			"Harry has 39 tattoos, Zayn has 28, Louis has 16 tattoos, Liam has 5 tattoos, and Niall has none",
			"Harry has a 22-year-old sister called Gemma.",
			"Harry has a Christmas jumper with skiing people on it",
			"Harry has no intent on playing Mick Jagger in a rumoured documentary",
			"Harry has size 10 feet",
			"Harry has the most followers on Twitter with 14,849,456 - August 5 2013",
			"Harry hasnt always wanted to be a singer. Before he took part in The X Factor he had ambitions to be a lawyer!",
			"Harry hates it when girls complain about their weight",
			"Harry hates olives",
			"Harry impressed 2 of 3 judges in the XFactor 1st round with Stevie Wonders Isnt She Lovely",
			"Harry is 5'10- or 178cm",
			"Harry is Marcel, Liam is Leeroy, Zayn is Veronica, Louis is Johny, and Niall is Harvey for Best Song Ever!",
			"Harry is an amazing flirt. He's near-seduced me very often, dammit!- Louis",
			"Harry is an occasional sleepwalker. Once, while staying the night at his girlfriend's house, he woke up naked in her mum's bed naked... Luckily he got back to his girlfriend's bed before her mum woke up",
			"Harry is learning to drive and is looking at cars to buy",
			"Harry is rumoured to only have 6 pairs of underwear, as he doesn't bother wearing any when he goes out. ;)",
			"@Harry_Styles is the 27th most followed person on Twitter , @onedirection is the 29th",
			"Harry is the scariest out of the boys when he is angry because he has a bad temper and a very loud voice.",
			"Harry knows how to knit :)",
			"Harry laughs a lot while he is on twitter because fans are so perverted to him most of the time",
			"Harry likes a girl with a good appetite",
			"Harry likes girls who wear pink",
			"Harry likes pink on a girl",
			"Harry likes to call his girlfriend -Baby- or -Sweetheart-. (I'm down with that --Gaby xo)",
			"Harry loves girls who are confident enough to walk up to him and talk to him",
			"Harry makes a brief cameo appearance in Ed Sheerans first Drunk video.  It was filmed backstage at Londons Shepherds Bush Empire",
			"Harry once told a girl he was gay because he wasn't interested in her",
			"Harry once walked out of the toilets and a fan asked him, Did you wash your hands? , He said No then rubbed his hands on her face as a joke",
			//"Harry reckons they should've picked the name -One Boner-",
			"Harry said -One day i would love to go to New Zealand, I've always wanted to go there!-",
			"Harry said that he admires a girl who can pee standing up",
			"Harry says he would happily date a fan! When asked he said: Yeah definitely, because if you like someone, you like someone. If theyre a fan it shouldnt make any difference",
			"Harry says he's awful at covering up his emotions",
			"Harry secretly knows how to knit",
			"Harry sleeps naked!",
			"Harry thinks Niall looks like Furby",
			"Harry thinks Zayn is the one who has shagged the most fans",
			"Harry thinks it's perfectly okay to kiss on the first date",
			"Harry thinks that 'Bambi' is the perfect first date movie because your date will get emotional and cuddle up to you",
			"Harry thinks that if he wasn't in One Direction people wouldn't like him as much as they do",
			"Harry thought that 'The Hunger Games' were about food",
			"Harry wants Louis to be his best man at his wedding in the future",
			"Harry wants his first child to be a girl, and would like to name her Darcy",
			"Harry was attacked by a goat when he was 10",
			"Harry was brought up in the village of Holmes Chapel in Cheshire",
			"Harry was once drunk and had an hour long chat with a cat",
			"Harry won't date anyone older than his Mum, who is 43",
			"Harry would like a younger 'soulmate' so he could feel like he protects her :) ",
			"Harry's dress up doll on 'Stardoll' has four nipples :)",
			"Harry's favorite Disney film is Dumbo",
			"Harry's favorite band is The Beatles",
			"Harry's favorite food is sweetcorn and his fave drink is apple juice",
			//"Harry's favorite song on the album is 'More Than This' and Niall's is 'One Thing'",
			"Harry's first word was 'cat' (Appropriate :])",
			"Harry's first word was cat",
			"Harry's hair almost got caught on fire the other night, but Zayn swooped in and saved the day!",
			"Harry's hair is so big, it doesn't even fit in the photos of his license",
			"Harry's motto in life is Work hard, play hard, be kind",
			"Harrys ex-girlfriend Caroline Flack was 15 years his senior  hes 17 and shes 32",
			"Harrys favorite TV show is Family Guy and his favorite movie is Love Actually - however, he tells everyone its Fight Club to seem more manly!",
			"Harrys favorite song of all time is Free Falling by John Mayer",
			"Harrys musical heroes are The Beatles and hes also a huge Coldplay fan",
			"I might just have wet myself ,Niall in reaction to getting a Number 1 single",
			"I once dreamed about a gigantic power ranger chasing me around- Zayn",
			"I would date Adele, she makes me weak at the knees- Harry",
			"If Harry wasn't in the band he would be at university studying and would work in a bakery",
			"If Liam could eat one thing for the rest of his life, he responded, Chocolate, because it's chocolatey",
			"If Liam could make an ice-cream flavor it would be Krisy-Kreme flavoured... what a weirdo :)",
			"If Liam was a girl he would date Louis, because he is funny",
			"If Liam wasn't in the band he would work in a factory building airplanes",
			"If Louis had a superpower, he would fly",
			"If Niall likes you he'll blush, flirt and laugh a lot",
			"If Niall wasn't in the band he would be a sound engineer",
			"If Zayn had to pick someone in the band to be his slave, he'd pick Liam",
			"If Zayn thinks a girl is attractive, he'll look down in a photo",
			"If Zayn was a girl he says that he'd date Liam",
			"If Zayn wasn't in the band he would be an English teacher",
			"If Zayn we're a girl he'd marry Liam",
			"If any of them gets hold of your number, Zayn is the most likely to call you",
			"If he wasn't in One Direction, Harry would be a sports physiotherapist",
			"If the world ended in 10 seconds what would you do? Niall said he'd fart",
			"If you went to school with Liam, he would probably be in the back, writing poems",
			"In 'Milkshake City' in London, they have a special One Direction drink you can buy",
				//"In December 2011 Niall had braces fitted on his teeth. Youll have to look very close to see them though as theyre white ones",
			"In One Thing, the producers wanted to change Niall's voice a bit, but Louis said No, his voice is beautiful, if you fix it, I won't sing`",
			"In a poll asking people if Harry should be the frontman of the band, 74% said no",
			"In primary school, he used to impress the ladies by balancing a spoon on his nose",
			"In school, Louis was dared to walk into the girls bathroom and make out with the first girl he saw. He ended up in detention",
			"In their 53 minute and 14 second long album, Niall got 1 minute and 24 seconds worth of solos",
			"Interviewer: Miley or Selena? Harry: Miley ",
			"Interviewer: Miley or Selena? Louis: Miley ",
			"Interviewer: Miley or Selena? Niall: Miley",
			"Interviewer: Miley or Selena? Zayn: Miley",
			"Is you scream in Harry's face he will most likely find you annoying... :/",
			//"It is confirmed that One Direction WILL be releasing a 3D movie   (and I think the title should be '1Din3D'!! :DD ok, sorry...)",
			"It was Nicole Scherzinger, the former Pussycat Doll who suggested that the boys should be put together at bootcamp to form one group",
			"It was guest judge, former Pussycat Doll Nicole Scherzinger, who suggested that Harry, Niall, Zayn, Liam and Louis should be put together as a group at X Factor bootcamp",
			"Japan is the first country in Asia they visited",
			"Justin Bieber first followed Zayn and we ran to tell Niall, who was in shower. He came out running wet and crying. - Liam",
			"Liam Payne was born on 29th August 1993. His star sign in Virgo",
			"Liam also took part in the 2008 series of The X Factor making it through to Simons house in Barbados where he was cruelly eliminated",
			"Liam always wishes on 11:11",
			"Liam and Louis have made Harry cry twice. By giving him a GIANT wedgie then ripping his Calvin Klein underwear and straightening his gorgeous curly hair in his sleep",
			"Liam and Niall both share the same middle name  James",
			"Liam bought Niall a life sized 'Barack Obama' for Christmas",
			"Liam can beatbox",
			"Liam can play a bit of piano and a bit of guitar",
			"Liam claims he owns pink hair straighteners",
			"Liam also cried while watching 'Toy Story 3'",
			"Liam gets emotional while singing 'Moments'.       (Bro we all do.)",
			"Liam has a fear of spoons",
			"Liam has a very unusual phobia  SPOONS! He admits its very strange and would like to invent an anti-spoons app for mobile phones.",
			"Liam has boxers that have the days of the week on them",
			"Liam is 5'10- or 178cm",
			"Liam is a secret Justin Bieber fan",
			"Liam is an avid fan of boxing",
			"Liam is the only one in the band that calls Harry 'Hazza'",
			"Liam is the only one who calls Harry 'Hazza'",
			"Liam once confessed to owning a pair of pink hair straighteners. Nice!",
			"Liam once cried in a restaurant because the waitress told him he couldn't eat his soup with a fork and he had to use a spoon",
			"Liam once cried while watching Marley & Me. Bless",
			"Liam only has 1 kidney after getting one removed. Hes completely teetotal and never touches a drop of alcohol, as he explains: Its just a choice to be on the safe side",
			"Liam owned two pink hair straighteners",
			"Liam sang Justin Timberlakes Cry Me A River in his 2010 audition and received a standing ovation. At bootcamp he covered Oasis Stop Crying Your Heart Out",
			"Liam says he's awful at flirting and he just goes shy.",
			"Liam says his accent is just a mix of all the boys because he spends so much time with them",
			"Liam spent his childhood in Wolverhampton, the birthplace of Led Zeppelin legend Robert Plant and Slades Noddy Holder",
			"Liam started dating backing dancer Danielle Peazer in December 2010.",
			"Liam thought that YOLO meant 'Yummy Oreos Love Origami'.",
			"Liam thinks he has big lips :)      Id kiss them anyday babes ;) HMU x",
			"Liam thinks he has big lips.",
			"Liam thinks it would be great to employ people to play games with them",
			"Liam thinks tattoos are 'Hot'.",
			"Liam thinks that snorting while laughing is the best laugh",
			"Liam used to practice kissing on the back of his hand. (Haven't we all?)",
			"Liam used to skip school to get away from being bullied by his classmates. (I bet those bullies regret it now!)",
			"Liam wants to call his first born 'Taylor'. Nawww :3",
			"Liam wants to get married in his mid-twenties.",
			"Liam's favorite Justin Bieber song is 'Somebody to Love'",
			"Liam's mom says Liam used to sing We are family, I am washing so I feel clean, in the shower",
			"Liam, Zayn, and Niall all have size 8 feet.",
			"Liam, please tell me you're not on cam without a top on. You absolute hoe.- Louis",
			"Liam: Niall can't have babies. Cause he doesn't have a, you know... He's got a you know...",
			"Liams celebrity crush is Leona Lewis and his man crush is stand-up comedian Michael McIntyre?! Nope, us neither!",
			"Liams favorite colour is purple.",
			"Liams favorite film is the Toy Story trilogy.",
			"Louis Tomlinson was born on 24th December 1991. Hes a Capricorn and the oldest member of One Direction",
			"Louis and Niall both get to start a song in Take Me Home",
			"Louis and Niall don't get many solos because their voices get girls pregnant.-Harry",
			"Louis and Zayn snuck out of their hotel room in Sydney and ended up getting lost",
			"Louis auditioned with Plain White Ts Hey There Delilah and got a clean sweep of yes from the judges",
			"Louis calls his mum every single night.",
			"Louis can play a bit of the piano.",
			"Louis celebrity crush is Diana Vickers and his man crush is Robbie Williams",
			"Louis cries when he watches romantic comedies.",
			"Louis describes Zayn's body as 'hot and spicy'.",
			"Louis doesn't see the point in flings, or short-term relationships",
			"Louis dreams about Harry and Niall the most.",
			"Louis fancies Natalie Portman.",
			"Louis hacked Eleanor's twitter and tweeted - I love Barney the Dinosaur",
			"Louis has 4 younger sisters.",
			"Louis has been bitten by chipmunks on several occasions.",
			"Louis has five sisters. Theyre called Lottie, Fizz, Daisy, Phoebe and Georgia",
			"Louis has no cousins.",
			"Louis is 5'9- or 174cm",
			"Louis is afraid of pigeons.",
			"Louis like it when girls wear glasses, real or not.",
			"Louis likes girls who eat carrots.       (ENOUGH WITH THESE JOKES, THEY SUCK NOW)",
			"Louis likes it when girls where glasses, fake or not.",
			"Louis once had a dream that SpongeBob was hitting him in the face, but when he woke up, it was just Niall wanting him to make food",
			"Louis pokes Harry's cheeks when he's bored.",
			"Louis sleep walks, and once Niall found him on his floor singing the Jungle Book in the middle of the night",
			"Louis sometimes lets fans smack his bum.",
			"Louis spent his first ever paycheck on adopting a chimpanzee called Larry",
			"Louis thinks Niall has the most beautiful eyes in the band",
			"Louis thinks that girls who blush are to die for.",
			"Louis wants to be able to fly.",
			"Louis wants to name his son either Lucas or Leo.",
			"Louis was brought up in Doncaster, South Yorkshire. Other famous people who hail from there include Jeremy Clarkson and Brian Blessed",
			"Louis was raised in Doncaster, South Yorkshire. The same place that TV personalities such as Jeremy Clarkson and Brian Blessed were brought up",
			"Louis' favorite Disney film is The Lion King.",
			"Louis' favorite country is France.",
			"Louis' favorite sandwich is prawn mayo with prawn chips.",
			"Louis' first pet was a dog named Ted. :)",
			"Louis' first word was cat.",
			"Louis' mother said that sisters have a hard time understanding why anyone would fancy their big brother",
			"Louis' mum says he's always preferred girls with brown hair",
			"Louis favorite band is The Fray.",
			"Louis middle name is William, Harrys is Edward and Zayns is Jawaad",
			"Most of One Direction's fan girls are on twitter NOT facebook",
			"My favorite one in the group was Zayn, until he stole my meal. Now my favorite is Harry. - Niall",
			"Niall Horan was born on 13th September 1993. Just like Liam, hes a Virgo",
			"Niall and Liam are the happiest people when they know they are gonna meet fans. They start jumping all around",
			"Niall and Louis blush really easily.",
			"Niall annoys Zayn by singing everything in opera. One morning Niall was singing in opera and Zayn slapped him ",
			"Niall avoids speaking in interviews because he swears too much and gets the whole band in trouble",
			"Niall can play guitar.",
			"Niall changed his Instagram from '@nialler1993' to '@niallhoran'",
			"Niall co-wrote 'Last First Kiss', 'Back For You' and 'Summer Love'",
			"Niall cried on the phone to his mummy after the Brits :) Naaaw NIALLER!! :( xo",
			"Niall cried while watching 'Finding Nemo'.",
			"Niall dislocated his knee playing soccer and now has a 67% chance it will dislocate itself randomly",
			"Niall doesn't like it when girls ask him if it's okay to hug him",
			"Niall doesn't like it when people tweet him ! Follow me follow me!!",
			"Niall failed history because he used to put his head down and sleep",
			"Niall goes after shy girls.",
			"Niall had the green one piece but traded with Zayn because he didn't want there to be any leprechaun jokes",
			"Niall had to wear sunglasses in the Kiss You music video because he flipped up the car visor to quick and bruised his eye",
			"Niall had two pet fish named Ben and Jerry but they accidentally died from him overfeeding them",
			"Niall has a Justin Bieber biography.",
			"Niall has a Nando's black card, which gives him free Nando's and is only given to celebrities",
			"Niall has a very bizarre good luck mascot  a pair of white socks. Erm, ok then!  ",
			"Niall has an older brother called Greg. Hes 23.",
			"Niall hates it when fans ask him for a follow back on Twitter",
			"Niall hates when a girl is afraid to eat in front of him",
			"Niall is 5'7- or 171cm",
			"Niall is a leftie but plays the guitar like a rightie :)",
			"Niall is a natural brunette.",
			"Niall is an accomplished guitar player while Harry plays the kazoo!",
			"Niall is left-handed.",
			"Niall is the first irish person to perform at an Olympic Closing Ceremony, to win a Brit, and first to win a VMA",
			"Niall is the main singer in Another World",
			"Niall is the only one of the group who is left-handed",
			"Niall just bought a house in LA next to the Kardashians, Ozzie Osbourne, and Jennifer Lopez",
			"Niall likes go follow people on Twitter who ask him how his day is going",
			"Niall likes it when girls can put on different accents and can speak different languages",
			"Niall likes shy girls.",
			"Niall never acts cool around celebrities and always fangirls",
			"Niall often speaks in his sleep",
			"Niall once offered to give up his hotel room for fans that were waiting in the freezing cold",
			"Niall once said in a n interview.. 'I will never date a model because models are perfect, perfect is boring' :DD",
			"Niall once told Liam that if he ever had a son, he'd name him after him",
			"Niall owns a life-size Obama statue",
			"Niall promised to name his son after Liam",
			"Niall got a tattoo on his wrist, it is a bar code with the word 'HUMAN' below",
			"Niall said 'I always defend the people I love, even though I'm about as terrifying as a ... baby penguin.' (He's way cuter than a baby penguin!)",
			"Niall said he screamed out loud when Justin Bieber followed him",
			"Niall said his girlfriend would look most beautiful with no makeup at all",
			"Niall said if he could sing any song to a fan, it's be the Barney theme tune whilst playing the guitar",
			"Niall sang Ne-Yos So Sick in the X Factor first round and received glowing praise from Louis Walsh. A big Oasis fan, he covered Champagne Supernova at bootcamp",
			"Niall says hes only read one book  the American classic To Kill A Mockingbird",
			"Niall screamed when Justin Bieber followed him",
			"Niall sings loud in the shower",
			"Niall slept with a teddy bear until he was twelve",
			"Niall talks about his day in his sleep",
			"Niall thinks Harry's constant nudity is contagious",
			"Niall used to sing to his girlfriend",
			"Niall usually ends his tweets with kisses",
			"Niall wants a girl who eats just as much as him.",
			"Niall was brought up in Mullingar in Ireland.",
			//"Niall's braces are coming off April 3rd",			
			"Niall's favorite part of his body is his eyes.",
			"Niall's favorite Pokemon is Snivy.",
			"Niall's home address: 24 Raithin Rd. Mullinger, West Meath, Ireland",
			"Niall's nephew is named Zeus Horan!",
			"Nialls favorite colour is blue.",
			"Nialls favorite movie of all time is Grease.",
			"Nialls ideal woman is Cheryl Cole and his man crush is Michael Buble.",
			"Nicki Manaj scares me as much as Paranormal Activity - Liam",
			"Numbers of Harry X-Factor audition: 165998",
			"Numbers of Liam X-Factor audition: 61898",
			"Numbers of Louis X-Factor audition: 155204",
			"Numbers of Niall X-Factor audition: 232677",
			"Numbers of Zayn X-Factor audition: 165616",
			"On October 1, 2011 they sold out their first tour in under 12 minutes",
			"Once a fan asked Zayn if he could ride the roller coaster of life with her and he said only if he could hold her hand.",
			"Once on tour Harry switched mics with Niall because the management gave Niall a mic with a lower volume :)",
			"One Direction are the brand ambassadors for the computer game Pokemon Black and White and have appeared on TV adverts and performed at events.",
			"One Direction bought an airplane. It cost 3 million pounds and is called - Air Force One Direction-",
			"One Direction finished third on The X Factor behind winner Matt Cardle and runner-up Rebecca Ferguson.",
			"1D have a bizarre pre-gig ritual of earing Haribo sweets together. -We do the sweets like they're drinks. We 'cheers them'. It's very strange but it's for good luck.-",
			"One Direction is the youngest ban to ever perform at the Olympic Games :)",
			"One Direction was the name that Harry suggested.",			
			"One Direction wrote 'More Than This', 'Taken' and 'Stole My Heart'.",
			//"One Directions 2011/2012 UK tour sold out in just 12 minutes when tickets went on sale in September.",
			"One thing Niall can't live without is his heart.",
			"One time Harry fell in front of the paparazzi, so the rest of the boys fell over too so that he wouldn't be embarrassed. :D",
			"One time a fan gave Niall a pair of boxers and said, You left them at home!",
			"Perrie often hacks Zayn's Twitter account and follows Directioners :) Awww Pez x",
			"Rita Ora covered WMYB :) ",
			"Seeing Niall cry is horrible, there should be a law against it - Harry",
			"Signing my first autograph was a bit awkward because I didn't have one. I didn't know what to do, so I just wrote -Harry- Harry.",
			"Simon Cowell believes 1D have what it takes to become one of the biggest boy bands on the planet.",
			"Somebody took a picture of Harry and Louis to a Gay Rights Parade :D",
			//"The One Direction 2012 Calendar is the best selling calendar of all time on Amazon.co.uk ",
			"The One Direction dolls are all 30cm in height and were created using laser-image face-sculpts for maximum authenticity.",
			//"The One Thing music video was shot at various locations in London on 28th November 2011 and premiered on YouTube 13th January 2012.",
			"The bands Twitter IDs are @Harry_Styles, @NiallOfficial, @zaynmalik, @Real_Liam_Payne and @Louis_Tomlinson.",
			//"The boys are reportedly singing all the songs on the full album and some favorites from The X Factor.",
			"The boys make fun of me because I'm a Belieber but when we met Joe Jonas, Liam was jumping everywhere. - Niall",
			"The boys once dared Louis to eat a script, something he had no problem doing.",
			"The boys think Niall would die first in a horror movie because he wouldn't know what the hell was going on.",
			"The boys think Zayn and Louis attract the most of the gay fans",
			"The boys would bang on the walls and jump on the floors to try and keep everyone awake in the X-Factor House.",

			"The lads have matching friendship bracelets",
			//"The last time the boys were in America, Harry got Ariana Grande's phone number",
			"The lyrics of WMYB were originally: You say hello, like you don't know, you made the lights in the room explode!!",
			"The other day during a concert, Harry had to go pee so badly that they stopped the concert and the boys sang 'Fresh Prince' so he could wee",			
			"The photo that has been sweeping Tumblr by storm of Niall smoking is infact... a FAKE! Someone photoshopped Zayn's hand onto a photo of Niall",
			"The producer's wanted Niall to go on a diet whilst on the X-Factor",
			"The rest of the band thought Louis was quiet when they first met",
			"The three things Liam can't live without are hair wax, Clearisil??, and Niall",
			"There are One Direction Lego figures",
			//"There will be a video diary every time they do a concert, there are 24 dates!",
			"They had to keep shooting the deep solo of Harry's in WMYB because he kept on spitting on her",
			"They nearly burned down the X-Factor House while making pizza",
			"They once sent Uncle Simon a birthday card with 2 pounds fifty in it, 50 pence for each",
			//"They will perform on the American X Factor soon",
			"This is a quote from Louis--some people say our fans are crazy, but the lads and I think their passionate.- Louis, You really understand us don'tcha",
			"Uncle Simon told Caroline Flack to stay away from Harry",

			"When Harry was younger he used to write on his toast with food colouring",
			"When Harry was younger he was kicked out of a supermarket for swearing at customers",
			"When Liam was younger he invited his whole class to his party but no one came",
			"When Louis and Eleanor were in Paris together, Louis screamed -I LOVE ELEANOR CALDER!!- Off of the Eiffel Tower",
			"When Louis is bored he pokes Harry's dimples to annoy him :)",
			"When Louis was planking on the railing of a boat, Harry rushed and pulled him down because he was scared he would get hurt",
			"When Matt was announced the winner of X Factor you can see Harry crying in the background",
			"When Niall gets homesick the rest of the boys speak to him in an Irish accent",
			"When One Direction met Michelle Obama, Harry asked her how she could order a pizza from the White House",
			"When Zayn was 6, he threw a TV out of a window",
			"When Zayny-Wayney was little he used to sleep walk :)",
			"When asked what their favorite word for boobs was, Niall replied Chicken fillets",
			"When describing his perfect girl, Harry kept on saying He instead of She. Larry anyone?",
			"When he's sad, Liam just imagines if babies were born with moustaches",
			"When the boys travel, they read fanfiction",
			"When they get swarmed by fans, the first thing Zayn does is look for Niall, because he knows how much it makes Niall nervous and scared",
			"When thinking of a name for the band Liam's dad suggested 'Status Single' which was taken into consideration",
			"Whenever Harry greets someone, he asks, You all right? instead of How are you?",
			"While filming WMYB Louis sent a message in a bottle. What a true pirate, he even wears stripes :)",
			"While in Sweden, Louis stole a duck from the hotel",
			"While on The X Factor, Harry had a big crush on judge Cheryl Cole and X Factor host Caroline Flack. Hes joked that his man crush is Louis Tomlinson!",
			//"White Eskimo' performed at a wedding in June 2010.",
			"With all the money Niall has made, he bought his mum a new car",
			"Would you rather kiss a girl or eat pizza? Harry replied 'kiss a girl' and Niall said he would eat pizza",
			"Zayn Malik was born on 12th January 1993. Hes a Capricorn just like Louis",
			"Zayn bought chocolate to fans that waited outside an arena",
			"Zayn can play the triangle",
			"Zayn cant swim",
			"Zayn dated fellow X Factor star Rebecca Ferguson for four months but the relationship ended when they drifted apart. Rebecca is six years older than Zayn",
			"Zayn does funny dancing when he is drunk",
			"Zayn doesn't like his lips",
			"Zayn fancies the pants off Megan Fox and has a secret man crush on Justin Timberlake",
			"Zayn feel very protective over Harry. He thinks people often forgets that Harrys the baby of the group, the youngest ",
			"Zayn had his first kiss when he was 9 :*",
			"Zayn had his radio on full blast and was dancing around to Night Fever totally naked when his cleaner walked in on him",
			"Zayn has a habit of sticking his tongue out",
			"Zayn has a soft spot for intelligent girls",
			"Zayn has a tattoo on his chest which says his Grandfathers name, in Arabic",
			//"Zayn has been smoking since he was 15",
			"Zayn has three sisters but no brothers. Theyre called Doniya, Waliyha and Safaa",
			"Zayn hates liars. If you lie to him, it would be hard to earn his trust again... Unless you're me.-Liam",
			"Zayn is 5'9- or 174cm",
			"Zayn is a cuddling sort of guy",
			"Zayn is afraid of clowns..",
			"Zayn likes girls who are intelligent",
			"Zayn likes pink nail polish on girls",
			"Zayn loves Build-A-Bear, he bought Harry and Niall one as a joke, and dressed them up, Niall's had a long blonde wig",
			"Zayn mimed 'hello' through the car window to a fan and she passed out",
			"Zayn once ate Niall last chip and he tried to eat Zayn's hand as punishment",
			"Zayn said that Niall's girlfriend would be the luckiest girl in the world",
			"Zayn says he's love it if a girl told him she loved his voice",
			"Zayn thinks short girls are the cutest",
			"Zayn used to eat paper all the time when he was younger",
			"Zayn used to write songs for his girlfriend",
			"Zayn want a girl who doesn't know she's beautiful , so he have an excuse to let her know shes beautiful all the time",
			"Zayn wanted the album to be called 'Zayn and the Boys'",
			"Zayn wants to quit smoking because he knows the fans don't like it",
			"Zayn was brought up in Bradford, West Yorkshire. Other famous Bradfordians include the Bront sisters, magician Dynamo and Gareth Gates",
			"Zayn wishes he could swap voices with Niall",
			"Zayn's Youtube account goes by the name of 'bradfordboizayn'",
			"Zayn's father is from Pakistan and his mother was born in England :)",
			"Zayn's favorite Disney film is Tarzan",
			"Zayn's favorite fast food is McDonald's",
			"Zayn's favorite food is chicken",
			"Zayn's favorite hobby is drawing",
			"Zayn's first kiss was when he was about 9",
			"Zayn's friends call him Superman, because when something bad happens, Zayn's always there to help",
			"Zayn's mum said that when he was 5, Zayn went to a park and got chased by a duck until he cried",
			"Zayn's real youtube account is 'bradfordboizayn'",
			"Zayn, Louis and Harry all support Manchester United. Liam is a West Bromich Albion fan while Niall follows Derby County",
			"Zayn: Yeah, 'cause I do that all the time... Wait, what abs?",
			"Zayns X Factor audition wasnt actually broadcasted on the main show. Only after he had progressed further in the competition was it then shown on The Xtra Factor",
			"Zayns X Factor audition wasnt broadcast on the main show. When he had progressed further it was retrospectively shown on spinoff The Xtra Factor",
			"Zayns favorite band of all time is *NSYNC.",
			"Zayns favorite book is Harry Potter",
			"Zayns fav song is Thriller by MJ, Harry loves Shine Crazy Diamond by Pink Floyd, Louis Look After You by The Fray, Nialls is Coldplays Viva La Vida & Liam prefers Happy Birthday as it means he will open presents",
			"Zayns name is actually spelt with an i (Zain). He reckons Zayn is more original and adopted it as his stage name",
			
			"Justin Bieber is still behind One Direction in the race to be crowned #MTVHottest  ",
			"One Direction Could Be The First Boy Band Worth $1 Billion once 2014 is on the books.",
			"If Liam could interview one pop star, it would be Usher",
			"Liam dream valentine would be with Kim Kardashian.",
			"Liam thinks he has the best dance moves in 1D, He told TOTP, I have the best dance moves--I'm the king of the dancefloor! My signature dance move is the 1-2-3 flick. You'll find it all over the internet..",
			"Best Song Ever have unofficially broken the record for the most watched music video in a single day",
			"1D Won Favorite Summer Tour, Favorite Love Song for Little Things, Favorite Group Single for Live While We're Young, and Favorite Music Group at the 2013 Teen Choice Awards",
			
			"one direction is the reason i know all you amazing people who i call my friends :)",
			"Hey , tweet us ur facts!",
			
			"you know    charity : water",
			
			"The fat guy that Neil 'plays' in the BSE video is actually his dad",
			"We all love Marcel",
			"Lux is Harry's niece",
			"If you ever meet Harry play marimba on your phone",
			"A girl who was on the 'crazy about one direction' documentary said that they were paid to read a script",
			"Liam  tells fans 'you should be proud' and says 1D 'couldn't give a f*ck' about *that crazy* documentary",
			"This Is Us earned 17 million $ in the first weekend ",
			" There's 898 unused hours of footage for This Is Us ",
			"Harry is basically an oversized seven year old boy, with the heart of a 90 year old man, and the sex appeal of a calvin klein model. ",
			" Harry said he found the orange that he was eating in the VMA's at the elevator.",
			"Interviewer: 'Who is most likely to twerk alone, at home, in front of the mirror?'   All:'Zain!'",
			"The guy who finds an orange in the elevator then offers a piece to Rihanna at the VMAs, everyone meet Harry Styles",
			"Can you imagine Harry lightly tapping Rihanna on the back and saying 'Um Hi do you want a piece of my orange ?",
			
						
	};
	
	// Methods - abilities;things the object can do
	public String getAnswers() {
		
		
		// el botton fue clicked asi que update con una answer
		String answer = "";
		
		//agrega una respuesta random , si, no depende
		Random randomGenerator = new Random(); //contruye un nuevo Random
		int randomNumber = randomGenerator.nextInt(mAnswers.length);
		
		//answer = Integer.toString(randomNumber);
		// convert numero a texto random
		
		
		/*if (randomNumber == 0) {
			answer = "Sip";
			
		}
		else if (randomNumber == 1) {
			answer = "Nop";
			
		}
		else if (randomNumber == 2) {
			answer = "Alomejor";
			
		}
		else {
			answer = "perdon esto es un error";
		}  
		todo esto lo cambio por la sig linea*/
		
		answer = mAnswers[randomNumber];
		
		return answer ;
	}

}
